language: php

sudo: false

addons:
    apt_packages:
        - parallel
        - language-pack-fr-base

env:
    global:
        - MIN_PHP=5.5.9

matrix:
    include:
        - php: hhvm
        - php: 5.5
        - php: 5.6
        - php: 7.0
    fast_finish: true

cache:
    directories:
        - .phpunit
        - php-$MIN_PHP

before_install:
    - if [[ $deps != skip ]]; then composer self-update; fi;
    - if [[ $deps != skip ]]; then ./phpunit install; fi;
    - export PHPUNIT=$(readlink -f ./phpunit)

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration phpunit.xml --coverage-text
