# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  - hhvm

env:
  - DB=mysql

notifications:
  email:
    - saytaine@gmail.com

on_success: [always|never|change] # default: change
on_failure: [always|never|change] # default: always

# optionally set up exclutions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: 7.0
    - php: hhvm

services:
- mysql

sudo: required


# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - php /home/travis/.phpenv/versions/5.4/bin/composer self-update
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test

  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://selenium-release.storage.googleapis.com/2.49/selenium-server-standalone-2.49.0.jar
  - php -S localhost:5555 -t public/ &
  - sleep 30

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script:
  - "java -jar selenium-server-standalone-2.49.0.jar -port 5555 -htmlSuite *firefox http://localhost:5555/ /home/travis/build/marvin-SL/planning/src/AppBundle/Tests/ ./result"
  - phpunit -c app/ src/
