# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  - hhvm

env:
  - DB=mysql

notifications:
  email:
    - saytaine@gmail.com

on_success: [always|never|change] # default: change
on_failure: [always|never|change] # default: always

# optionally set up exclutions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: 7.0
    - php: hhvm

services:
- mysql

sudo: required


# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - echo "Install and setup apache"
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-intl php5-gd php5-idn php-pear php5-imagick php5-imap
  - php5-mcrypt php5-memcache php5-ming php5-ps php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl
  - sudo a2enmod rewrite
  - sudo sed -i -e "s,/var/www,/home/travis/build/cioddi/travis-ci-phpunit-selenium-template,g" /etc/apache2/sites-available/default
  - sudo sed -i -e "s,AllowOverride[ ]None,AllowOverride All,g" /etc/apache2/sites-available/default
  - sudo /etc/init.d/apache2 restart
  - php /home/travis/.phpenv/versions/5.4/bin/composer self-update
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - php -S localhost:8000 -t public/ &
  - wget http://selenium-release.storage.googleapis.com/2.49/selenium-server-standalone-2.49.0.jar


# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script:
    - java -jar selenium-server-standalone-2.49.0.jar > /dev/null 2>&1 &
    - phpunit -c app/ src/
