# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  - hhvm

env:
  - DB=mysql

# optionally set up exclutions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: 7.0
    - php: hhvm

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - php /home/travis/.phpenv/versions/5.4/bin/composer self-update
  - composer install
  - mysql -e "create database IF NOT EXISTS cmwplanning;" -uroot; fi


# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit -c app/ src/
