# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  - hhvm

env:
  - DB=mysql

notifications:
  email:
    #- saytaine@gmail.com

on_success: [always|never|change] # default: change
on_failure: [always|never|change] # default: always

# optionally set up exclutions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: 7.0
    - php: hhvm

services:
- mysql

sudo: required


# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
  - sudo a2enmod rewrite
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

  - php /home/travis/.phpenv/versions/5.4/bin/composer self-update
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
  - php app/console assetic:dump

  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5
  - serverUrl='http://localhost:4444'
  - wget http://selenium-release.storage.googleapis.com/2.49/selenium-server-standalone-2.49.0.jar
  - "java -jar selenium-server-standalone-2.49.0.jar > /dev/null &"
  - sleep 5

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script:
  - phpunit -c app/ src/
