app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AppBundle/Resources/config/Admin/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

adesigns_calendar:
  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"
