app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# fos_user_registration_register:
#     path:      /inscription
#     defaults:  { _controller: FOSUserBundle:Registration:register }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_profile_show:
    path:      /admin/account/
    defaults:  { _controller: AppBundle:Account:index, _method: POST }
