user_calendar_show:
  path:        /{slug}/show
  defaults:  {_controller: AppBundle:User/Calendar:show}

user_calendar_mobile:
  path:        /{slug}/mobile
  defaults:  {_controller: AppBundle:User/Calendar:mobile}
