admin_user_index:
    path:    /
    defaults:   {_controller: AppBundle:Admin/User:index}

admin_user_new:
    path:    /new
    defaults:   {_controller: AppBundle:Admin/User:new}

admin_user_edit:
    path:        /{id}/edit
    defaults:  {_controller: AppBundle:Admin/User:edit}

admin_user_delete:
    path:        /{id}/delete
    defaults:  {_controller: AppBundle:Admin/User:delete}
