admin_calendar_index:
    path:    /index
    defaults:  {_controller: AppBundle:Admin/Calendar:index}
    options:
        expose: true

admin_calendar_new:
     path:        /new
     defaults:  {_controller: AppBundle:Admin/Calendar:new}

admin_calendar_show:
  path:        /{slug}/show
  defaults:  {_controller: AppBundle:Admin/Calendar:show}

admin_calendar_edit:
   path:        /{slug}/edit
   defaults:  {_controller: AppBundle:Admin/Calendar:edit}
