admin_calendar_new:
     path:        /new
     defaults:  {_controller: AppBundle:Admin/Calendar:new}

admin_calendar_index:
    path:    /index
    defaults:  {_controller: AppBundle:Admin/Calendar:index}
