admin_account:
    path:        /
    defaults:  {_controller: AppBundle:Admin/Account:index}

admin_account_change_password:
    path:        /change-password
    defaults:  {_controller: AppBundle:Admin/Account:ChangePassword}
