admin_event_new:
      path:    /new
      defaults:  {_controller: AppBundle:Admin/Event:new}

admin_event_xmlWriter:
    path:       /xmlWriter
    defaults:   {_controller: AppBundle:Admin/Event:xmlWriter }

admin_event_edit:
    path:    /{id}/edit
    defaults:  {_controller: AppBundle:Admin/Event:edit}
    options:
        expose: true

admin_event_delete:
 path:        /{id}/delete
 defaults:  {_controller: AppBundle:Admin/Event:delete}
