admin_event_new:
      path:    /new
      defaults:  {_controller: AppBundle:Admin/Event:new}

admin_event_xmlWriter:
    path:       /xmlWriter
    defaults:   {_controller: AppBundle:Admin/Event:xmlWriter }
