index:
      path:      /
      defaults:  { _controller: AppBundle:Default:index }
      options:
          expose: true

admin:
    resource: "@AppBundle/Resources/config/routing/Admin/admin.yml"
    prefix:   /

User:
    resource: "@AppBundle/Resources/config/routing/User/user.yml"
    prefix:   /
