index:
      path:      /
      defaults:  { _controller: AppBundle:Default:index }
      options:
          expose: true

xmlWriter:
    path:       /xmlWriter
    defaults:   {_controller: AppBundle:Default:xmlWriter }
