admin_dashboard:
    path:       /admin/dashboard
    defaults:  {_controller: AppBundle:Admin:index}

admin_create_calendar:
     path:        /admin/calendar/new
     defaults:  {_controller: AppBundle:Admin:createCalendar}

admin_create_event:
      path:    /admin/event/new
      defaults:  {_controller: AppBundle:Admin:createEvent}
