admin_dashboard:
    path:       /admin/dashboard
    defaults:  {_controller: AppBundle:Admin/Dashboard:index}

admin_calendar_new:
     path:        /admin/calendar/new
     defaults:  {_controller: AppBundle:Admin/Calendar:new}

admin_calendar_show:
    path:    /admin/calendar/show
    defaults:  {_controller: AppBundle:Admin/Calendar:show}     

admin_event_new:
      path:    /admin/event/new
      defaults:  {_controller: AppBundle:Admin/Event:new}

admin_event_xmlWriter:
    path:       /admin/event/xmlWriter
    defaults:   {_controller: AppBundle:Default/Event:xmlWriter }

admin_subject_new:
      path:    /admin/subject/new
      defaults:  {_controller: AppBundle:Admin/Subject:new}

admin_teacher_new:
      path:    /admin/teacher/new
      defaults:   {_controller: AppBundle:Admin/Teacher:new}

admin_create_classRoom:
      path:    /admin/class-room/new
      defaults:    {_controller: AppBundle:Admin:createClassRoom}
