admin_dashboard:
    path:       /admin/dashboard
    defaults:  {_controller: AppBundle:Admin:index}

admin_calendar_new:
     path:        /admin/calendar/new
     defaults:  {_controller: AppBundle:Admin/Calendar:new}

admin_event_new:
      path:    /admin/event/new
      defaults:  {_controller: AppBundle:Admin/Event:new}

admin_create_subject:
      path:    /admin/subject/new
      defaults:  {_controller: AppBundle:Admin:createSubject}

admin_create_teacher:
      path:    /admin/teacher/new
      defaults:   {_controller: AppBundle:Admin:createTeacher}

admin_create_classRoom:
      path:    /admin/class-room/new
      defaults:    {_controller: AppBundle:Admin:createClassRoom}
